#!/usr/bin/env python3
"""Build the Operations Extended Response Anki deck (.apkg).

Content mirrors business-studies/operations-extended-response-notes.md,
which was compiled solely from the student's Google Drive resources.
Four sub-decks: Theory Definitions / Links / Qantas Evidence / Essay Structure.
"""
import genanki

MODEL = genanki.Model(
    1607392319,
    'Operations ER (Basic)',
    fields=[{'name': 'Front'}, {'name': 'Back'}],
    templates=[{
        'name': 'Card 1',
        'qfmt': '<div class="q">{{Front}}</div>',
        'afmt': '{{FrontSide}}<hr id="answer"><div class="a">{{Back}}</div>',
    }],
    css="""
.card { font-family: -apple-system, Segoe UI, Arial, sans-serif; font-size: 19px;
        text-align: left; color: #1a1a1a; background-color: #fdfdfd; padding: 14px; }
.q { font-weight: 600; }
.a { margin-top: 6px; }
b { color: #b30000; }
.tag { display:inline-block; font-size: 13px; font-weight: 700; color:#fff;
       background:#8a0e0e; border-radius: 4px; padding: 1px 7px; margin-bottom: 6px; }
ul { margin: 4px 0 4px 18px; padding: 0; }
li { margin: 3px 0; }
.night_mode .card { color:#eee; background-color:#2b2b2b; }
.night_mode b { color:#ff8080; }
""")

D_THEORY = genanki.Deck(2059400110, 'Operations ER::1. Theory Definitions')
D_LINKS = genanki.Deck(2059400111, 'Operations ER::2. Links (Influences ↔ Processes ↔ Strategies)')
D_QANTAS = genanki.Deck(2059400112, 'Operations ER::3. Qantas Evidence (FY-labelled)')
D_ESSAY = genanki.Deck(2059400113, 'Operations ER::4. Essay Structure & Mnemonics')


def add(deck, front, back):
    deck.add_note(genanki.Note(model=MODEL, fields=[front, back]))


T = '<span class="tag">THEORY</span><br>'
L = '<span class="tag">LINK</span><br>'
Q = '<span class="tag">QANTAS</span><br>'
E = '<span class="tag">ESSAY</span><br>'

# ----------------------------------------------------------------------------
# 1. THEORY DEFINITIONS
# ----------------------------------------------------------------------------
theory = [
 ('Define <b>operations</b> (intro definition — memorise word-for-word)',
  '"Operations refers to the <b>business processes that involve transformation and production of goods and services</b> in both the manufacturing and service sectors."<br><br>Alt: "Operations management involves overseeing and controlling the transformation of inputs into outputs; focusing on both efficiency and quality to ensure business success."'),
 ('Define <b>influences on operations</b>',
  '"The various <b>internal and external factors</b> that impact the way a business manages and conducts its operational processes."'),
 ('Define <b>globalisation</b>',
  '"The <b>removal of barriers of trade between nations</b>… characterised by an increasing integration between national economies and a high degree of transfer of capital, labour, intellectual capital and ideas, financial resources and technology."<br><br>Simpler: the increasing interconnection and interdependence of global businesses and markets.'),
 ('Define the <b>supply chain</b> and the <b>global web</b>',
  '<b>Supply chain</b>: "the range of suppliers a business has and the nature of its relationship with those suppliers."<br><b>Global web</b>: "the network of suppliers chosen on the basis of <b>lowest overall cost, lowest risk and maximum certainty</b> in quality and timing of supplies."'),
 ('Define <b>technology</b> (as an influence)',
  '"Technology is the <b>design, construction and/or application of innovative devices, methods and machinery</b> upon operations processes."'),
 ('What are the TWO levels of technology (influence)?',
  '<b>Administrative level</b>: planning technologies (Gantt charts, CPA), office + software technologies → "assist with organisation, planning and decision making to help <b>control</b> the operational processes."<br><b>Processing level</b>: machinery, robotics, CAD, CAM, CIM → "improve <b>accuracy, speed and efficiency</b> of production and therefore improved outputs."'),
 ('Define <b>quality expectations</b>',
  '"The influence that <b>consumers</b> have on a business, as their expectations for a product will determine the way in which that product is <b>designed, created and delivered</b>."'),
 ('Quality expectations: the 3 dimensions for GOODS',
  '<ul><li><b>Quality of design</b> — how well the concept has been developed</li><li><b>Fit for purpose</b> — does it do what the advertising claims</li><li><b>Durability</b> — how long it lasts with reasonable use</li></ul>'),
 ('Quality expectations: the 3 dimensions for SERVICES',
  '<ul><li><b>Professionalism</b> of the provider</li><li><b>Reliability</b> of the provider</li><li><b>Level of customisation</b> — how well the customer\'s needs are fulfilled</li></ul>'),
 ('Define <b>cost-based competition</b>',
  '"Derived from determining the <b>breakeven point (TC = TR)</b> and then applying strategies to create <b>cost advantages</b> over competitors."<br><br>Key tension: reduce costs <b>without compromising quality</b>.'),
 ('List 5 ways operations can reduce costs (cost-based competition)',
  '<ul><li>Eliminate waste</li><li>Bulk-buy inputs</li><li>Produce high-volume output</li><li>Automated production systems</li><li>Achieve economies of scale</li></ul>'),
 ('Define <b>government policies</b> (influence)',
  '"Methods used by government that <b>encourage the operations function to be more innovative and competitive</b>, as it ultimately produces more income for the nation."<br><br>Areas: taxation, WHS, public health, environment, employment relations, trade.'),
 ('Define <b>protection</b> (trade)',
  '"Any <b>artificial advantage</b> given by a country\'s government to domestic industries to protect them from international competition."<br><br>Removal of tariffs/quotas has forced Australian businesses to cut operating costs to compete.'),
 ('Government policies vs legal regulation — what\'s the difference?',
  '<b>Government policies</b> = broad guidelines and objectives; <b>indirect</b> impact.<br><b>Legal regulation</b> = specific, compulsory, enforced laws; <b>direct</b> impact.'),
 ('Define <b>legal regulation</b> and <b>compliance costs</b>',
  '"Legal regulation (compliance) refers to the <b>range of laws with which a business must comply</b>."<br>"Compliance costs are the <b>expenses associated with meeting the requirements</b> of legal regulations."'),
 ('Name the 4 key Acts for operations (and what each covers)',
  '<ul><li><b>Work Health and Safety Act 2011</b> — safe work environment, risk management, training</li><li><b>Fair Work Act 2009</b> — fair employment, minimum wage, dignity and respect</li><li><b>Environment Protection and Biodiversity Conservation Act 1999</b> — pollution, waste, conservation</li><li><b>Competition and Consumer Act 2010</b> — consumer guarantees on outputs</li></ul>'),
 ('Define <b>environmental sustainability</b> (influence)',
  '"A sustainable business practice whereby the <b>resources a business consumes in the operations process today will not affect the quantity of the resource for future generations</b>."'),
 ('Define <b>corporate social responsibility</b> (CSR)',
  '"<b>Open and accountable business actions</b> based on <b>respect for people, the community and the environment</b>. It involves doing <b>more than just complying</b> with the law and regulations."'),
 ('CSR sub-point: <b>legal compliance vs ethical responsibility</b>',
  '<b>Legal compliance</b>: "laws a business must legally adhere to, or else there are penalties" — mandatory, government-enforced.<br><b>Ethical responsibility</b>: "the obligation to adopt honesty, integrity and transparency to be morally correct despite legal requirements" — voluntary, corporate conscience.<br><br>Grey zone: outsourcing to relaxed-law countries cuts compliance costs — legal but ethically frowned upon; "reputation whiplash may be a net negative."'),
 ('CSR sub-point: environmental sustainability AND social responsibility',
  '<b>Environmental</b> = going beyond requirements to protect the environment / reduce carbon footprint.<br><b>Social</b> = "initiatives that benefit society including <b>fair labour practices, community engagement and philanthropy</b>."<br><br>Evaluation: adds cost and cuts short-term profit BUT "reputation is the most significant intangible asset – <b>goodwill</b>."'),
 ('Define <b>operations processes</b> and <b>inputs</b>',
  '"Operations processes are those processes involved <b>directly with transformation of inputs into outputs</b>."<br>"Inputs are the <b>resources used in the transformation (production) process</b>."'),
 ('Define <b>transformed resources</b> (+ the three)',
  '"The inputs which are <b>changed or converted</b> into something else, or acted upon."<br><br><b>M</b>aterials, <b>I</b>nformation, <b>C</b>ustomers.'),
 ('Define <b>materials</b>, <b>raw materials</b> and <b>intermediate goods</b>',
  '"Materials are the <b>basic elements used in the production process</b>" (collectively "direct materials").<br><b>Raw materials</b>: essential substances in their unprocessed state.<br><b>Intermediate goods</b>: goods already manufactured, used in further processing.'),
 ('Define <b>information</b> as a transformed resource',
  '"The <b>knowledge gained from research, investigation and instruction</b>, which results in an increase in understanding."<br><br><b>External</b>: ABS statistics, media. <b>Internal</b>: financial reports, customer feedback, KPIs.<br>It "influences other inputs and the transformation process by guiding decisions."'),
 ('How are <b>customers</b> an input?',
  'Their needs and desires "<b>drive</b>" the operations of the business — their choices shape additional inputs and processes; and customers are literally transformed (physically, emotionally, psychologically — e.g. moved from city A to city B).'),
 ('Define <b>transforming resources</b> (+ the two)',
  '"The inputs that <b>carry out the transformation process</b> — used to transform other resources but not themselves part of the finished product."<br><br><b>H</b>uman <b>R</b>esources + <b>F</b>acilities.'),
 ('Define <b>human resources</b> and <b>facilities</b> (as inputs)',
  '<b>HR</b>: "employees who provide the <b>skills, knowledge, capabilities and labour</b> to convert materials into goods/services."<br><b>Facilities</b>: "the <b>plant (factory/office) and machinery</b> used in operations processes" — decisions on location, layout, capacity.'),
 ('Define <b>volume</b> (4 V\'s) + volume flexibility + lead time',
  '"Volume refers to the <b>amount of a product that is produced</b>."<br><b>Volume flexibility</b>: how quickly the process adjusts to demand changes.<br><b>Lead time</b>: time from order placed to order fulfilled.<br><br>High volume → standardisation + economies of scale; low volume → customisation, higher unit cost.'),
 ('Define <b>variety</b> (4 V\'s) + mix flexibility',
  '"Variety refers to the <b>number of different models and variations</b> offered."<br><b>Mix flexibility</b>: the mix of products made or services delivered.<br><br>More variety = more customers but higher cost per unit.'),
 ('Define <b>variation in demand</b> (4 V\'s)',
  '"The <b>change in demand</b> from customers by time of day, season, or other external/internal influences."<br><br>Volatile demand → operations must be flexible; predictable demand → stable, efficient operations.'),
 ('Define <b>visibility</b> (4 V\'s) + touchpoints',
  '"The <b>touchpoints where a business interacts with a customer</b>."<br><b>Direct</b>: face-to-face, calls, surveys. <b>Indirect</b>: online reviews, sales data.<br><br>High visibility → customer-focused, higher-cost operations; low visibility → back-end efficiency focus.'),
 ('Job vs batch vs mass production (mapped to the 4 V\'s)',
  '<ul><li><b>Job</b>: items made individually — low volume, high variety (designer dress)</li><li><b>Batch</b>: identical products produced simultaneously in groups — medium/medium (bakery)</li><li><b>Mass/flow</b>: large quantities of standardised products on assembly lines — high volume, low variety</li></ul>'),
 ('Define <b>sequencing</b> and <b>scheduling</b>',
  '<b>Sequencing</b> = "the <b>order</b> in which activities in the operations process occur."<br><b>Scheduling</b> = "the <b>length of time</b> activities take within the operations process."<br><br>Shortcut: sequencing = order, scheduling = time.'),
 ('Define a <b>Gantt chart</b> + its limitation',
  '"Outlines the activities to be performed, the <b>order</b> in which they should be performed and <b>how long</b> each is expected to take" — bar chart of tasks vs time; good for assigning resources and monitoring progress.<br><br>Limitation: <b>does NOT show relationships between tasks</b> (CPA does).'),
 ('Define <b>critical path analysis</b> + what the critical path is',
  '"A sequencing and scheduling technique showing what tasks need to be done, how long they take and what order is necessary."<br><br>The <b>critical path</b> = the <b>longest sequence of dependent tasks</b> — which is therefore the shortest possible total completion time. It highlights tasks that cannot afford delays.'),
 ('Define <b>task design</b>',
  '"Classifying job activities in ways that make it <b>easy for an employee to successfully perform and complete</b> the task" — breaking work into jobs that each contribute to the final goal.'),
 ('Name and define the 4 <b>process layouts</b>',
  '<ul><li><b>Process/functional</b>: machines grouped by function (hospital wards)</li><li><b>Product</b>: equipment in the sequence of operations — assembly line, high volume</li><li><b>Fixed position</b>: product stays still, workers/materials come to it (building a house)</li><li><b>Office</b>: arrangement of workstations for information flow</li></ul>'),
 ('Define <b>monitoring</b> (+ example KPIs)',
  '"The process of <b>measuring actual performance against planned performance</b>", using KPIs.<br><br>Typical operations KPIs: wait times, inventory turnover, defect rates, process flow rates.'),
 ('Define <b>control</b> (processes)',
  '"Control occurs when <b>KPIs are assessed against predetermined targets</b> and <b>corrective action</b> is taken if required."'),
 ('Define <b>improvement</b> + <b>bottleneck</b>',
  '"The <b>systematic reduction of inefficiencies and wastage</b>, poor work processes and the elimination of any bottlenecks."<br><b>Bottleneck</b>: a point in a process where the flow of work is delayed or breaks down.<br><br>Dimensions: time, process flow, quality, cost, efficiency.'),
 ('Model definition: <b>monitoring, control and improvement</b> (memorise)',
  '"Monitoring, control and improvement refers to the <b>systematic oversight of the operations process</b>, making adjustments where needed in order to <b>increase the efficiency of transforming inputs into outputs</b>."'),
 ('Define <b>outputs</b>',
  '"The finished goods or services produced by the operations function that have a <b>value to customers greater than the cost of inputs</b>."<br><br>Profitability condition: output revenue &gt; input expenditure.<br>Two subtler outputs: customer service + warranties.'),
 ('Define <b>customer service</b> (output)',
  '"How well a business <b>meets and exceeds the expectations</b> of customers."<br><br>Fact to drop: one dissatisfied customer shares it with ~<b>11</b> potential customers. Measured via NPS/satisfaction surveys.'),
 ('Define <b>warranties</b> (output) + the consumer guarantees',
  '"Business <b>promises to correct any defects</b> in the good or service they deliver."<br><br>Under the <b>Competition and Consumer Act 2010</b>: products must match description, be fit for purpose, and be free from defects.'),
 ('Define <b>operations strategies</b>',
  '"The strategies that operations managers may use to <b>achieve operations goals and broader business goals</b>… An effective operations strategy will give a business a <b>competitive advantage</b>."'),
 ('Define <b>performance objectives</b>',
  '"Goals that <b>relate to particular aspects of the transformation processes</b>" — quantifiable targets/KPIs that gauge and guide operational efficiency.'),
 ('List the 6 performance objectives + one-liners',
  '<ul><li><b>Quality</b> — being right</li><li><b>Speed</b> — being fast</li><li><b>Dependability</b> — being on time</li><li><b>Flexibility</b> — being able to change</li><li><b>Customisation</b> — being able to provide more options</li><li><b>Cost</b> — being productive</li></ul>'),
 ('Define <b>quality</b> (performance objective) + 3 dimensions',
  '"How well designed, manufactured and functional goods are, and the degree of skill in which services are delivered."<br><ul><li><b>Quality of design</b></li><li><b>Quality of conformance</b> — consistency to the prescribed design (Big Mac identical globally)</li><li><b>Quality of service</b> — reliable, prompt, meets client needs</li></ul>'),
 ('Define <b>speed</b> (performance objective)',
  '"The time it takes for the production and operations processes to <b>respond to changes in market demand</b>."<br><br>Goals: reduced wait times, shorter lead times, faster processing.'),
 ('Define <b>dependability</b> (performance objective) + how it\'s measured',
  '"How <b>consistent and reliable</b> a business\'s products are."<br><br>Goods → durability, measured by <b>warranty claims</b>. Services → consistency, measured by <b>complaints</b>.'),
 ('Define <b>flexibility</b> and <b>customisation</b> (performance objectives)',
  '<b>Flexibility</b>: "how quickly operations processes can <b>adjust to changes in the market</b>" (volume, variety, product changes).<br><b>Customisation</b>: "creation of <b>individualised products</b> to meet specific customer needs"; <b>mass customisation</b> = customisation at scale (car colour options).'),
 ('Define <b>cost</b> (performance objective)',
  '"The <b>minimisation of expenses</b> such that operations processes are conducted <b>as cheaply as possible</b>."<br><br>Achieved by: minimising waste, reducing supplier costs, managing inventory, maximising flexibility.'),
 ('Define <b>new product or service design and development</b>',
  '"Creating and introducing new offerings to meet market demands or technological advancements — <b>researching customer needs, designing a product to fulfil those needs, testing it and then implementing it</b>."'),
 ('Consumer approach vs capability approach (product design)',
  '<b>Consumer approach</b>: market research determines the features and quality customers want.<br><b>Capability approach</b>: changes in technology allow more advanced product functionality.'),
 ('Explicit vs implicit service (service design)',
  '<b>Explicit service</b>: the <b>tangible</b> aspect — application of time, expertise, skill, effort.<br><b>Implicit service</b>: the <b>intangible</b> psychological feeling of being looked after.<br><br>The more standardised a service, the lower the operating costs.'),
 ('Define <b>supply chain management</b> (verbatim — contains the process link)',
  '"SCM involves <b>integrating and managing the flow of supplies throughout the inputs, transformation processes and outputs</b> in order to best meet the needs of customers."'),
 ('Define <b>logistics</b> + its components',
  '"The part of the supply chain that focuses on <b>moving inputs, resources and outputs through the supply chain as quickly as possible</b>."<br><br>Components: transportation, storage, warehousing, distribution centres (short-term), materials handling, packaging.'),
 ('Define <b>e-commerce</b> (SCM) + e-procurement',
  '"The <b>buying of inputs via the internet</b>."<br><b>B2B e-procurement</b>: electronic stock management auto-reorders when stock is low → prevents supply shortfalls.<br><b>B2C</b>: online selling removes intermediaries/wholesalers → cheaper prices.'),
 ('Define <b>global sourcing</b>',
  '"Businesses <b>purchasing supplies or services without being constrained by location</b>" — buying from wherever best meets requirements.<br><br>Risks: exchange rates, differing laws, longer lead times.'),
 ('Define <b>outsourcing</b>',
  '"The use of <b>external providers</b> (third parties or contractors) <b>to perform business activities</b>."<br><br>Rationale: cheaper, more efficient, provider specialises in that function.'),
 ('Advantages of outsourcing (4)',
  '<ul><li><b>Cost reduction</b> (especially labour)</li><li><b>Focus on core activities</b> → productivity and innovation</li><li><b>Access to specialist expertise</b></li><li><b>Flexibility</b> to scale up/down without permanent staff</li></ul>'),
 ('Disadvantages of outsourcing (5)',
  '<ul><li>Less <b>control over quality</b></li><li><b>Dependency</b> on the external provider</li><li>Communication / cultural barriers</li><li><b>Security risks</b> sharing sensitive data</li><li>Possible <b>reputation damage</b></li></ul>'),
 ('Define <b>leading edge technology</b> + benefits',
  '"Technology that is the <b>most advanced or innovative at any point in time</b>."<br><br>Benefits: better quality, less waste, replaces costly labour, <b>"improves the four V\'s"</b>. Downsides: risky (untested) and expensive.'),
 ('Define <b>established technology</b> + examples',
  '"Technology that has been <b>developed and widely used and is simply accepted without question</b>" — reliable, refined, lower risk.<br><br>Examples: barcodes, spreadsheets, email, standard booking systems, CAD/CAM.'),
 ('Define <b>inventory management</b> + inventory',
  '"The system and strategies that manage the <b>ordering, storage and recovery of the materials</b> used in production."<br><b>Inventory (stock)</b>: raw materials + work-in-progress + finished goods on hand.'),
 ('Advantages of <b>holding stock</b> (just-in-case)',
  '<ul><li>Always meet customer demand (ready supply)</li><li>Bulk-buy discounts</li><li>Buffer against supply interruptions and price rises</li><li>Production continuity; meets seasonal spikes</li></ul>'),
 ('Disadvantages of <b>holding stock</b>',
  '<ul><li>Storage/warehousing/insurance costs</li><li>Spoilage and damage risk</li><li>Obsolescence</li><li>"<b>Stock is cash used ineffectively</b>" — capital tied up</li></ul>'),
 ('Define <b>FIFO</b> + its effects',
  '"Assumes the <b>first goods purchased are the first goods sold</b>, so the cost of each unit sold is the first cost recorded."<br><br>Matches real physical flow; ideal for <b>perishables</b>; lower COGS → higher reported profit (and more tax); legal in Australia.'),
 ('Define <b>LIFO</b> + its status in Australia',
  '"Assumes the <b>last (most recent) goods purchased are the first goods sold</b>."<br><br>Higher COGS → lower reported profit and tax. <b>Banned by the ATO under Australian Accounting Standards (since 1986)</b> — it distorts the true flow of inventory.'),
 ('Define <b>JIT</b> (just-in-time)',
  '"Ensures that the <b>exact amount of material inputs will arrive only as they are needed</b> in the operations process."<br><br>Minimal holding costs, frees working capital, exposes defects — but requires ultra-reliable suppliers and excellent forecasting.'),
 ('Define <b>quality management</b>',
  '"The maintenance of <b>consistency, reliability and sustainability</b> to ensure the product <b>meets the quality expectations of the customer</b>." (The definition itself links back to the quality expectations influence.)'),
 ('Define <b>quality control</b> + its 3 stages',
  '"The implementation, monitoring and corrective action required to uphold a certain level of quality" — <b>detection</b>.<br><ul><li><b>Feed-forward</b>: before production begins (inputs)</li><li><b>Concurrent</b>: during work in progress (transformation)</li><li><b>Feedback</b>: checking the final product (outputs)</li></ul>'),
 ('Define <b>quality assurance</b>',
  '"Ensuring the product has a certain level of quality <b>before it even reaches the market</b>" — proactive/<b>prevention</b>; universal standards applied globally; <b>ISO 9001</b> certification.'),
 ('Define <b>quality improvement</b> + TQM\'s 4 elements',
  '"Focuses on <b>continuous improvement and total quality management</b> so quality is always improving."<br><b>TQM</b>: a holistic approach — quality is every employee\'s responsibility. Four elements: <b>benchmarking, employee empowerment, customer focus, continuous improvement</b>.'),
 ('Define <b>Kaizen</b> and <b>Six Sigma</b>',
  '<b>Kaizen</b>: Japanese philosophy of continuous, incremental improvements to enhance efficiency.<br><b>Six Sigma</b>: data-driven decisions to reduce defects and increase quality.'),
 ('Rugby analogy for QA / QC / QI',
  '<b>Quality assurance</b> = game prep (proactive).<br><b>Quality control</b> = in-game adjustments (reactive).<br><b>Quality improvement</b> = reviewing the tape and implementing feedback (continuous).'),
 ('Overcoming resistance to change: the two families of resistance',
  '<b>Financial</b>: financial costs, purchasing new equipment, redundancy payments, retraining, reorganising plant layout.<br><b>Psychological</b>: inertia.'),
 ('Define the financial costs of change (equipment, redundancy, retraining, layout)',
  '<ul><li><b>Purchasing new equipment</b> (capital cost) — will it be recouped through quality/flexibility/waste/lead-time gains? Consider leasing.</li><li><b>Redundancy payments</b> — compensation "required by law" when roles disappear.</li><li><b>Retraining</b> — new skills for new practices; training time hits profitability.</li><li><b>Reorganising plant layout</b> — reconfiguration cost + workflow disruption.</li></ul>'),
 ('Define <b>inertia</b> (resistance to change)',
  '"The <b>psychological constraint of moving forward</b> — a feeling of uncertainty and fear in change… people resist due to comfort in the current environment, <b>even if it is not the most efficient way of completing the operations process</b>."'),
 ('What is <b>Lewin\'s change model</b>?',
  '<b>Unfreeze → Change → Refreeze</b> (prepare → implement → solidify). Plus: communicate why change is necessary, involve employees, set achievable goals from a SWOT, use change agents.'),
 ('Define <b>global factors</b>',
  '"The strategies a business can use in a global environment <b>to improve the operations process</b>."<br><br>The four: global sourcing, economies of scale, scanning and learning, R&amp;D.'),
 ('Define <b>economies of scale</b> + why it happens',
  '"The <b>cost advantages</b> a business obtains <b>due to their scale of operation</b> — as production increases, cost per unit falls."<br><br>Why: fixed costs spread over more units + bulk-buying discounts.'),
 ('Define <b>scanning and learning</b>',
  '"The systematic process of acquiring information about changes and trends in external economic conditions."<br><br><b>Scanning</b> = looking overseas for new ideas and trends. <b>Learning</b> = implementing them by changing processes domestically.'),
 ('Define <b>research and development</b> (R&amp;D)',
  '"The systematic work undertaken to <b>improve or create new products and production processes</b>, or to extend product life cycles." Costly → mostly done by larger firms.'),
]

# ----------------------------------------------------------------------------
# 2. LINKS
# ----------------------------------------------------------------------------
links = [
 ('LINK: How does <b>globalisation</b> impact operations PROCESSES?',
  '<b>Inputs</b>: access to global resources, diverse supplier networks, technology transfer.<br><b>Transformation</b>: affects the 4 V\'s, task design, sequencing, technology, process layout.<br><b>Outputs</b>: global market reach, customisation of products, efficiency in distribution.'),
 ('LINK: Which STRATEGIES answer <b>globalisation</b>?',
  'Global factors (global sourcing, economies of scale, scanning &amp; learning, R&amp;D), supply chain management, and outsourcing.'),
 ('LINK: How does <b>technology (influence)</b> impact processes?',
  '<b>Administrative</b> technology → <b>controls</b> the transformation process (Gantt/CPA planning).<br><b>Processing</b> technology → improves <b>accuracy, speed and efficiency</b> of production "and therefore improved outputs."'),
 ('LINK: How do <b>quality expectations</b> impact processes, and which strategy pairs with them?',
  'They "shape the <b>design, production and delivery</b>" of the product → drive the <b>monitoring, control and improvement</b> stage and the quality of <b>outputs</b> (customer service, warranties).<br><br>Classic pairing: quality expectations → <b>quality management</b> (control/assurance/improvement + TQM).'),
 ('LINK: How does <b>cost-based competition</b> reach the processes?',
  'Cheaper <b>inputs</b> + efficient/automated <b>transformation</b> + high-volume <b>outputs</b> → lower cost per unit. "Achieved by streamlining processes, reducing waste, adopting efficient technologies."<br><br>Strategy responses: outsourcing, JIT, economies of scale, cost performance objective.'),
 ('LINK: How do <b>government policies</b> impact processes?',
  'They change the cost/availability of <b>inputs</b> (fuel taxes, subsidies), the rules of the <b>transformation process</b> (WHS, employment relations), and demand for <b>outputs</b> (travel restrictions, economic policy).'),
 ('LINK: How does <b>legal regulation</b> impact processes?',
  'Safety training + protective equipment shape the <b>transforming resources</b> (HR, facilities); pollution/waste rules constrain the <b>transformation</b>; consumer-law guarantees attach to <b>outputs</b> (warranties).'),
 ('LINK: How does <b>environmental sustainability</b> impact processes?',
  'Changes the <b>inputs</b> used (sustainable fuel, fuel-efficient aircraft as facilities) and forces eco-friendly <b>transformation</b> — energy-efficient processes, optimised flight planning, waste handling in outputs.'),
 ('LINK: SCM → processes (why is SCM\'s definition itself a link?)',
  'Because SCM "manages the flow of supplies <b>throughout the inputs, transformation processes and outputs</b>" — it touches every stage of the operations process by definition.'),
 ('LINK: Outsourcing → processes',
  'Shifts stages of the <b>transformation process</b> to specialist third parties → lower cost per unit, potentially higher quality, BUT less control over that process stage. From the cheat sheet: outsourcing → sequencing &amp; scheduling, technology, task design.'),
 ('LINK: Technology strategy → processes (the quotable sentence)',
  'Technology "improves <b>quality</b>, increases <b>speed</b>, allows <b>flexibility</b>, provides <b>dependability</b>, reduces <b>costs</b> and allows <b>customisation</b> → productivity gains." Leading edge tech also directly "<b>improves the four V\'s</b>."'),
 ('LINK: Inventory management → processes',
  'Controls the flow and cost of <b>material inputs</b> into the transformation process. <b>JIT</b> is how the <b>speed</b> and <b>cost</b> objectives reach the process (shorter lead times, minimal holding costs).'),
 ('LINK: Quality control\'s 3 stages ↔ the 3 process stages',
  '<b>Feed-forward</b> = inputs (before production) · <b>Concurrent</b> = transformation (work in progress) · <b>Feedback</b> = outputs (final product).'),
 ('LINK: Warranties → process improvement (the feedback loop)',
  '"The number of <b>warranty claims</b> gives an indication to operations managers that there are <b>issues within the operations process</b>" — outputs feed back into monitoring, control and improvement.'),
 ('LINK: Performance objectives → processes',
  'By definition: "Performance objectives are goals that <b>relate to particular aspects of the transformation processes</b>" — each objective is a KPI on the process itself.'),
 ('LINK: Which strategies deliver each performance objective?',
  '<ul><li><b>Speed</b> ← technology + JIT</li><li><b>Dependability</b> ← established technology + inventory management</li><li><b>Customisation</b> ← flexible supply chains + technology</li><li><b>Cost</b> ← SCM, outsourcing, economies of scale, waste minimisation</li><li><b>Quality</b> ← product design, supplier choice, Six Sigma</li></ul>'),
 ('LINK: R&amp;D vs scanning and learning (one-liner to quote)',
  '"<b>Research and development improves processes; scanning and learning improves strategies.</b>"'),
 ('LINK: Global factors → processes',
  'By definition global factors are "strategies used in a global environment <b>to improve the operations process</b>": global sourcing → inputs; economies of scale → inputs (unit cost); R&amp;D → monitoring, control, improvement.'),
 ('LINK: Cheat-sheet strategy → process quick-reference',
  '<ul><li>QC → control + inputs · QA → monitoring + inputs · QI → improvement + inputs</li><li>E-commerce → volume, streamlined inputs, technology</li><li>Logistics → task design, sequencing &amp; scheduling</li><li>Retraining → sequencing &amp; scheduling · Redundancies → technology, process layout</li><li>EOS → inputs · R&amp;D → monitoring, control, improvement</li></ul>'),
 ('RULE: What makes an influence→strategy link "make sense"? (with a good and bad example)',
  'Match interests, don\'t clash them.<br><br>GOOD: quality expectations → quality management (both about standards).<br>BAD: quality expectations → cost-based competition (cutting costs clashes with raising quality).'),
 ('LINK: The full influence → strategy → process map (4 big ones)',
  '<ul><li>Quality expectations → quality management → monitoring/control/improvement + outputs</li><li>Technology influence → technology strategy → 4 V\'s, sequencing &amp; scheduling</li><li>Globalisation → global factors/SCM/outsourcing → inputs (global web) + outputs (reach)</li><li>Cost-based competition → outsourcing/JIT/EOS → input costs + transformation efficiency</li></ul>'),
 ('LINK: HSC 2019-style performance objective ↔ strategy pairs (Qantas-ready)',
  '<ul><li>Leading-edge technology ↔ <b>speed + quality</b> (Project Sunrise: −4 hrs travel, better cabins)</li><li>Global sourcing ↔ <b>cost + long-term dependability</b> (SAF secured to 2028+)</li><li>SCM/logistics ↔ <b>flexibility + customisation</b> (10,000 suppliers absorbed the 132% flying rebound)</li></ul>'),
]

# ----------------------------------------------------------------------------
# 3. QANTAS EVIDENCE
# ----------------------------------------------------------------------------
qantas = [
 ('QANTAS (FY25): domestic market position?',
  'Qantas Group carried <b>60% of Australia\'s domestic passengers in H1 FY25</b>.'),
 ('QANTAS (FY25): international growth stats?',
  '<b>+220,000 international seats</b> added in FY25; 2025 international capacity of <b>7.1 million seats</b> is 2.5% above pre-COVID.'),
 ('QANTAS (FY25): A321XLR numbers?',
  '<b>28 A321XLRs delivered in 2025</b> — each burns ~<b>17% less fuel</b>, carries <b>+15% more passengers</b>, and delivers ~$7M EBIT benefit per aircraft.'),
 ('QANTAS: cost transformation — total cut + FY25 plan?',
  'Cut <b>$5 billion in costs over the past 6 years</b> (cost base −20%); a further <b>$400M cost-out planned for 2025</b>.'),
 ('QANTAS (FY24): revenue + profit?',
  'Revenue <b>$21.94 billion (+10.7%)</b>; underlying profit before tax <b>$2.08 billion</b>; 51.8M passengers carried.'),
 ('QANTAS (FY24): unit cost?',
  '<b>9.73c per Available Seat Kilometre</b>, down 4.5% from 10.19c in FY23.'),
 ('QANTAS: dependability turnaround (2024 vs 2022)?',
  'On-time performance <b>80%</b> and cancellations <b>2.5%</b> in 2024 — vs <b>44% OTP and 6.7% cancellations in 2022</b>. (Pre-pandemic benchmark: 85% OTP.)'),
 ('QANTAS (FY24): customer satisfaction recovery stats?',
  'Domestic NPS up <b>24 points</b> across FY24; Q4 FY24 OTP +10 pts and NPS +22 pts vs Q2 FY24.'),
 ('QANTAS (FY24): baggage improvement + cause?',
  'Mishandled bags down <b>30%</b> FY24 vs FY23, driven by <b>RFID baggage tracking + app</b> (launched 2023).'),
 ('QANTAS (FY24): digital + lounge investment?',
  '<b>$230M</b> in digital/customer initiatives; <b>$100M</b> on lounges (42 domestic + 9 international).'),
 ('QANTAS: fleet renewal program?',
  '<b>$12 billion fleet renewal from 2024</b> (up to $15b / ~300 aircraft over the decade); 11 new aircraft delivered FY24; fleet age 15 yrs vs competitors\' 10.'),
 ('QANTAS: load factor (capacity matched to demand)?',
  'Revenue Seat Factor steady at <b>83% in FY23 and FY24</b> (vs 68% in FY22, 84% pre-COVID).'),
 ('QANTAS: Jetstar cost-competition stats?',
  'Jetstar sold <b>11 million fares under $100 in FY24</b>; ~20.4M Jetstar passengers; A321s cut Jetstar cost per seat ~20%.'),
 ('QANTAS: cost structure (top 3 expenses)?',
  'Staff <b>26%</b>, aircraft operating <b>23%</b>, fuel <b>22%</b> of total costs.'),
 ('QANTAS: the ACCC "ghost flights" case?',
  '<b>$100M civil penalty + $20M refunds</b> (ordered Oct 2024) for selling tickets on <b>8,000+ already-cancelled flights</b>. Use for: legal regulation, CSR (compliance failure).'),
 ('QANTAS: the illegal outsourcing case?',
  '<b>1,700 ground handlers outsourced in 2020</b> (Swissport, 55 airports), saving ~<b>$100M/year</b>; the <b>High Court ruled (Sept 2023)</b> it breached the <b>Fair Work Act</b> — the largest illegal-dismissal finding against an Australian company.'),
 ('QANTAS: outsourcing quality effects (both directions)?',
  'Upside: aircraft damage fell <b>0.8 → 0.4 per 1,000 flights</b>; lost bags <b>12 → 5 per 1,000</b>.<br>Downside: the High Court ruling + reputational damage; also outsources heavy maintenance offshore (Manila A380 work) and IT (IBM/India).'),
 ('QANTAS: Project Sunrise (full detail)?',
  '<b>12 Airbus A350-1000s</b> for 19-hour non-stop Sydney–London/New York; launching <b>mid-2026</b>; cuts travel time ~<b>4 hours</b>; peak spend <b>$1.2bn into FY25–26</b>; wellness zones and redesigned cabins. Kept on schedule with Gantt charts + CPA.'),
 ('QANTAS: emissions targets (Climate Action Plan)?',
  '<b>Net zero by 2050</b>; <b>25% cut in emissions by 2030</b> (vs 2019); <b>10% SAF by 2030, 60% by 2050</b>; fuel efficiency improving 1.5% p.a. (16.5% above 2019).'),
 ('QANTAS: SAF (sustainable aviation fuel) deals?',
  '<b>500M litres p.a. secured from 2028</b>; <b>20M litres from California starting 2025 (FY25)</b>; BP London deal (10M litres); <b>$400M Climate Fund</b>; $290M Airbus partnership for an Australian SAF industry; $50M mustard-seed SAF research.'),
 ('QANTAS: waste/plastics targets?',
  '<b>Zero single-use plastics by 2027</b> — 200M+ items already eliminated.'),
 ('QANTAS: government policy evidence (protection + costs)?',
  'Government <b>blocked Qatar Airways\' extra flights (2023–24)</b>; domestic aviation fuel taxed 6c/L; <b>Sydney Airport Curfew Act 1995</b> (11pm–6am, fines to $550,000); ~$2.7bn COVID assistance incl. ~$900M JobKeeper.'),
 ('QANTAS: globalisation competition stats?',
  '<b>62 international airlines</b> served Australia in 2024 (vs 52 in 2000); <b>70% of the 40 airlines flying to/from Australia receive home-government support — Qantas does not</b>.'),
 ('QANTAS: global reach stats?',
  'Oneworld alliance → <b>900 destinations in 170+ countries</b>; Emirates partnership (Dubai hub lowers costs); international revenue <b>$8.7bn FY24</b>; 70% of assets geared to the global market, 50% to Asia.'),
 ('QANTAS: fuel exposure stat (globalisation)?',
  '<b>$2.55 billion</b> fuel bill in 1H FY24, driven by geopolitical tensions; 3.5 billion litres of fuel used a year (2022).'),
 ('QANTAS: sequencing &amp; scheduling systems?',
  '<b>Sabre Air Flight Suite</b> automates flight scheduling (one of 200 airlines); <b>Integrated Operations Centre</b> monitors every aircraft globally; <b>35-minute domestic turnaround target</b> — clean → refuel → engineer check before every takeoff.'),
 ('QANTAS: quality control evidence?',
  '<b>A-check inspections every 400–600 flight hours (200–300 flights)</b>; 2019 fleet-wide 737 wing-crack inspections (33 checked, 2 grounded).'),
 ('QANTAS: quality assurance evidence?',
  '<b>IATA Operational Safety Audit (IOSA)</b> registration + <b>CASA</b> benchmarks (200+ maintenance audits); <b>ISO 9001</b> standards.'),
 ('QANTAS: quality improvement evidence?',
  '<b>Kaizen adopted 2024</b>; Lean Six Sigma benchmarking; Skytrax ranking recovered <b>24th (2024) → 14th (2025)</b>; cancellations 7.1% → 2.5% during 2022; ranked <b>#2 safest airline in the world 2025</b>.'),
 ('QANTAS: JIT inventory evidence?',
  'Fuel managed <b>just-in-time</b> (2023 Annual Report: fuel approach "centred around a Just-In-Time inventory system"); JIT spare parts save ~<b>$20M annually</b>.'),
 ('QANTAS: spare parts scale + FIFO?',
  '<b>28,000 component + 60,000 expendable part numbers</b> across ~70 global stocking locations; Servigistics forecasting → <b>94% parts availability</b>. <b>FIFO for in-flight meals</b> (perishables).'),
 ('QANTAS: supply chain scale?',
  '~<b>10,000 supply partners, ~$12 billion annual spend</b>; direct fuel pipeline Kurnell refinery → Sydney Airport (750M litres storage); aircraft globally sourced (Airbus/Boeing, bought in USD).'),
 ('QANTAS: e-commerce stats?',
  '<b>97% of sales online</b>; ~<b>70% of bookings via qantas.com/app</b>; 8.5M monthly website visits; TripADeal bookings +60%.'),
 ('QANTAS: overcoming resistance to change — the costs?',
  '<b>$1 billion in redundancy payments since 2020</b> (~9,000 redundancies); ~<b>$275M/year on training</b>; new <b>$20M Sydney training centre (2024)</b> trains 4,500 pilots/cabin crew a year; $12bn fleet renewal.'),
 ('QANTAS: economies of scale evidence?',
  'Flying hours <b>+25%</b> (2023→24) while unit costs fell <b>5.2%</b>; fixed costs ($525M Sydney terminal lease, hangars, training) spread across ~<b>820 daily flights</b>; 60% domestic share H1 FY25.'),
 ('QANTAS: scanning and learning evidence?',
  '<b>Emirates alliance</b> (leverages Dubai infrastructure); <b>Jetstar Asia</b> positioned in a region forecast for 50% aviation growth over 10 years; NPS benchmarked against Emirates.'),
 ('QANTAS: R&amp;D evidence?',
  '<b>$50M mustard-seed SAF research</b>; <b>Constellation</b> AI flight-planning system (built with the Australian Centre for Field Robotics) saving 2% fuel/yr; Project Sunrise as ultra-long-haul R&amp;D; FlightPulse app avoided 5.71M kg CO2 in year one.'),
 ('QANTAS: inputs examples (all 5 categories)?',
  '<b>Materials</b>: fuel (3.5bn L/yr), meals · <b>Information</b>: ECAM + ACARS flight data · <b>Customers</b>: 51.8M passengers FY24, 16.4M frequent flyers · <b>HR</b>: 27,000+ staff (93% Australia-based) · <b>Facilities</b>: 347 aircraft, terminals, hangars, $20M simulator centre.'),
 ('QANTAS: 4 V\'s evidence?',
  '<b>Volume</b>: ASK +21% FY24; Sydney–Melbourne every 15–30 min (2nd highest-revenue route in the world) · <b>Variety</b>: 4 seat classes, 65 domestic + 35 international destinations · <b>Variation</b>: 132% flying increase FY23 vs FY22; school-holiday peaks (4.7M pax July 2022) · <b>Visibility</b>: NPS +24 pts; low-visibility baggage/maintenance runs on efficiency.'),
 ('QANTAS: variation in demand — the big rebound stat?',
  '<b>132% increase in flying activity FY23 vs FY22</b> — handled thanks to backup suppliers across the 10,000-partner supply chain. (Also the model conclusion-closer stat.)'),
 ('QANTAS: outputs / warranties evidence?',
  'Service guarantees instead of typical warranties: refunds/compensation for cancellations, <b>$50–100/day baggage-delay compensation, up to $2,000 for lost baggage</b>; Qantas Freight revenue $1.2B FY24, <b>+11% in 1H FY25</b>; Loyalty EBIT $255M 1H FY25.'),
 ('QANTAS: reputation/trust numbers (quality expectations both ways)?',
  'Customer trust fell <b>74% (Aug 2023) → 47% (June 2024)</b>; RepTrak score recovered 12 points to <b>67/100</b> in FY24 — quality expectations punish you when unmet.'),
 ('QANTAS: CSR evidence (positive + counter)?',
  'Positive: <b>45,000 free flights</b> after the Rex/Bonza collapses (2024); 220+ repatriation flights FY22; UNICEF "Change for Good" ~<b>$38M over 21 years</b>; Reconciliation Action Plan.<br>Counter: illegal outsourcing ruling + ghost-flights penalty = compliance failures.'),
 ('QANTAS: intro "glaze" sentence (memorise one)',
  '"Qantas Group, carrying <b>60% of Australia\'s domestic passengers (H1 FY25)</b> and operating in over 150 countries worldwide, proves an appropriate case study…"<br><br>Alt: "Qantas\' ability to obtain <b>$21.94 billion in revenue (FY24, up 10.7%)</b> indicates their success in…"'),
 ('QANTAS: which stats are the MOST RECENT in your notes, and what\'s missing?',
  'Newest = <b>FY25 / 1H FY25</b> (year ended 30 June 2025): 60% domestic share, +220k intl seats, 28 A321XLRs, $400M 2025 cost-out, 20M L Californian SAF, Freight +11%.<br><br><b>No FY26 half-year figures exist in the source notes</b> — FY25 is "this financial year\'s" results.'),
]

# ----------------------------------------------------------------------------
# 4. ESSAY STRUCTURE & MNEMONICS
# ----------------------------------------------------------------------------
essay = [
 ('The INTRODUCTION formula (4 sentences)',
  '<ol><li><b>Define operations</b> (memorised).</li><li>Introduce your 2–4 dot points with a slight link — say "<b>businesses</b>", NOT Qantas: "In response to the operations influences of …, it is essential that businesses employ the operational strategies of …"</li><li>"<b>Glaze</b>" Qantas in 1 sentence with a stat.</li><li><b>Answer the question + directive</b> (dot-point level only).</li></ol>'),
 ('The BODY formula per syllabus point (3-part SAQ)',
  '<ol><li><b>Numbered heading</b> — e.g. "1.0 – The Effectiveness of Quality Management Strategies in Response to Quality Expectations"</li><li><b>Theory paragraph</b>: define influence → build → linking sentence → define strategy → build → link to question + directive.</li><li><b>Sub-dot-point paragraph</b> (e.g. "1.1 – Quality Control"): "As a [dot point], [sub-dot-point] refers to…" → build → link.</li><li><b>Qantas paragraph</b> (no new heading): specific action + stat(s) + judgement.</li></ol>'),
 ('The QANTAS paragraph rules (3)',
  '<ol><li><b>Be specific</b>: "don\'t say Qantas use quality control strategies, say they use maintenance and repairs for their damaged aircraft."</li><li><b>Minimum 1 stat</b> (more is better) — e.g. A-checks every 400–600 flight hours.</li><li><b>Answer the directive</b>: "based on the above criteria, Qantas have been astoundingly effective in responding to…"</li></ol>'),
 ('How many syllabus dot points should you cover, and what\'s the mark scale?',
  '<b>2–4 dot points</b> depending on time. Tested rough scale: <b>2 ≈ 16/20 · 3 ≈ 18/20 · 4 ≈ 20/20</b>. Keep BALANCE between the two dot-point areas (e.g. influences AND strategies).'),
 ('The CONCLUSION formula (3 parts)',
  '<ol><li>Answer question + directive at the "<b>businesses</b>" level (dot points only).</li><li>Answer again with <b>Qantas</b> and the sub-dot-points you used.</li><li><b>Final stat</b> backing your judgement — model closer: "Under the guidance of Vanessa Hudson, Qantas has seen a shift away from the negative commentary with a 132% increase in flying."</li></ol>'),
 ('The 3 marking criteria (what the marker rewards)',
  '<ol><li><b>Theory + directive + links</b> between the two syllabus dot points.</li><li><b>Stats</b> — "everyone can get this just by memorizing stats."</li><li><b>Structure, syllabus coverage, links that make sense, and balance</b> between the two areas.</li></ol>'),
 ('Exam craft rules (3)',
  '<ul><li><b>Underline/highlight</b> headings and evaluative words.</li><li><b>Define the directive verb</b> before writing (e.g. describe = characteristics &amp; features).</li><li><b>Continually address the directive</b> throughout.</li></ul>'),
 ('Mnemonic: the operations INFLUENCES',
  '<b>"GTG LECoQ + CSR"</b> — Globalisation, Technology, Government policies, Legal regulation, Environmental sustainability, Cost-based competition, Quality expectations + Corporate Social Responsibility.'),
 ('Mnemonic: the operations STRATEGIES',
  '<b>"POGO SQuINT"</b> — Performance Objectives, Outsourcing, Global factors, Overcoming resistance to change, SCM, Quality management, Inventory management, New product/service design &amp; development, Technology.'),
 ('Mnemonic: the PERFORMANCE OBJECTIVES',
  '<b>"QueSaDela Football CClub"</b> — Quality, Speed, Dependability, Flexibility, Customisation, Cost.'),
 ('Mnemonic: the INPUTS',
  '<b>"MIC"</b> — Materials, Information, Customers (transformed) + <b>"F + HR"</b> — Facilities, Human Resources (transforming).'),
 ('Linking scaffolds (3 sentence starters)',
  '<ul><li>"In response to the influence of …, businesses should employ … which refers to …"</li><li>"To bolster the process of …, businesses should employ …"</li><li>"As a [syllabus dot point], [sub-dot-point] refers to …"</li></ul>'),
 ('Judgement/evaluation phrases (4)',
  '<ul><li>"Based on the above criteria, Qantas have been astoundingly effective in responding to the influence of …"</li><li>"Qantas has implemented … and achieved … (cause and effect)"</li><li>"By …, Qantas have proven their ability to successfully attain …"</li><li>"…illustrates the success of Qantas\' … strategy"</li></ul>'),
 ('Past operations extended-response questions (6)',
  '<ul><li>HSC 2023 — To what extent do influences on operations affect business success</li><li>HSC 2022 — Explain the importance of operations processes that can maintain a competitive advantage</li><li>HSC 2019 — Analyse the relationship between performance objectives and operations strategies</li><li>HSC 2017 — Analyse the effect of globalisation on operations management</li><li>Roseville 24 — Assess strategies management can use to respond to influences on operations</li><li>Barker 24 — Assess the use of operations strategies to improve operations processes</li></ul>'),
]

for f, b in theory:
    add(D_THEORY, T + f, b)
for f, b in links:
    add(D_LINKS, L + f, b)
for f, b in qantas:
    add(D_QANTAS, Q + f, b)
for f, b in essay:
    add(D_ESSAY, E + f, b)

pkg = genanki.Package([D_THEORY, D_LINKS, D_QANTAS, D_ESSAY])
pkg.write_to_file('Operations-ER-Anki-Deck.apkg')
total = len(theory) + len(links) + len(qantas) + len(essay)
print(f'Wrote Operations-ER-Anki-Deck.apkg with {total} cards '
      f'({len(theory)} theory / {len(links)} links / {len(qantas)} Qantas / {len(essay)} essay)')
